import { ClientLayout } from "@/components/features/ClientLayout/ClientLayout";
import { getLocaleFromCookie, getMessages } from "@/lib/server-i18n";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocaleFromCookie();
  const messages = await getMessages(locale);

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-main`}
      >
        <main className="p-6 h-screen flex justify-center items-center">
          <ClientLayout messages={messages} locale={locale}>
            {children}
          </ClientLayout>
        </main>
      </body>
    </html>
  );
}
