import { ClientLayout } from "@/components/features/ClientLayout/ClientLayout";
import { ThemeProvider } from "@/components/features/ThemeProvider";
import { getLocaleFromCookie, getMessages } from "@/lib/server-i18n";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocaleFromCookie();
  const messages = await getMessages(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-main`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="px-6 pt-14 pb-16 mb-5 min-h-screen flex justify-center items-start">
            <ClientLayout locale={locale} messages={messages}>
              {children}
            </ClientLayout>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
