"""add_accepting_applications_to_teams

Revision ID: d900747c6d6e
Revises: 8ff23ff78aa7
Create Date: 2026-06-07 06:30:19.730396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd900747c6d6e'
down_revision: Union[str, Sequence[str], None] = '8ff23ff78aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('accepting_applications', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'accepting_applications')
    # ### end Alembic commands ###
